language: cpp

install:
  - wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
  - tar -xzvf release-1.10.0.tar.gz
  - pushd googletest-release-1.10.0 && cmake CMakeLists.txt && make && popd

env:
  - GOOGLETESTDIR=googletest-release-1.10.0

scripts:
  - make && make test

